name: 🐛 Bug Report
description: Report a bug or issue
title: "[BUG] "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's wrong?
      placeholder: When I run...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Run command...
        2. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Copy and paste any error messages
      render: shell
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: v0.1.0
    validations:
      required: true