[book]
title = "Joule Profiler"
authors = ["Jeremy Woirhaye", "François Gibier"]
language = "en"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["src/js/mermaid.min.js", "src/js/mermaid-init.js", "src/js/pagetoc.js"]
additional-css = ["src/css/book.css", "src/css/pagetoc.css"]